[tool.poetry]
name = 'H1st-Contrib'
version = '22.2.22.1'
description = 'H1st Contrib'
authors = ['Aitomatic, Inc. <engineering@aitomatic.com>']
license = 'Apache-2.0'
readme = 'README.md'
homepage = 'https://github.com/h1st-ai/contrib'
repository = 'https://github.com/h1st-ai/contrib'
packages = [
  {include = 'h1st_contrib'}
]


[tool.poetry.dependencies]
Python = '>= 3.8, < 3.10'

# H1st
H1st = {url = 'https://github.com/h1st-ai/h1st/archive/main.zip'}

# Data Processing
NumPy = '*'
PyArrow = '^7.0.0'
PySpark = '^3.2.1'

# ML/DL
Imbalanced-Learn = '^0.9.0'
SciKit-Learn = '^1.0.2'
TensorFlow = '^2.8.0'

# AWS deps: often conflict w/ other deps, so need separate installation
# AWSCLI = '*'
# Boto3 = '*'

# misc/other
CLICK = '^8.0.4'
Python-DotEnv = '^0.19.2'
'Ruamel.YAML' = '^0.17.21'
Tqdm = '^4.62.3'


[tool.poetry.scripts]
h1st = 'h1st_contrib.cli:h1st_cli'


[build-system]
requires = [
  'Poetry-Core >= 1.0.7',
]
build-backend = 'poetry.core.masonry.api'
