[tool.poetry]
name = 'H1st-Contrib'
version = '22.5.8'
description = 'H1st Contrib'
authors = ['Aitomatic, Inc. <engineering@aitomatic.com>']
license = 'Apache-2.0'
readme = 'README.md'
homepage = 'https://github.com/h1st-ai/h1st-contrib'
repository = 'https://github.com/h1st-ai/h1st-contrib'
packages = [
  {include = 'h1st_contrib'}
]


[tool.poetry.dependencies]
Python = '>= 3.8, < 3.10'

# H1st
H1st = {url = 'https://github.com/h1st-ai/h1st/archive/main.zip'}

# Data Processing
NumPy = '*'
PyArrow = '^8.0.0'
PySpark = '^3.2.1'

# ML/DL
Imbalanced-Learn = '^0.9.0'
SciKit-Learn = '^1.0.2'
TensorFlow = '^2.8.0'

# Django & related
Django = '^4.0.4'
Django-Configurations = '^2.3.2'
Django-CORS-Headers = '^3.11.0'
Django-Environ = '^0.8.1'
Django-Extensions = '^3.1.5'
DjangoRESTFramework = '^3.13.1'
Django-Silk = '^4.3.0'
DRF-Writable-Nested = '^0.6.3'

# DB-related
PsycoPG2-binary = '^2.9.3'

# AWS deps: often conflict w/ other deps, so need separate installation
# AWSCLI = '*'
# Boto3 = '*'

# misc/other
CLICK = '^8.1.3'
Python-DotEnv = '^0.20.0'
'Ruamel.YAML' = '^0.17.21'
Tqdm = '^4.64.0'


[tool.poetry.scripts]
h1st = 'h1st_contrib.cli:h1st_cli'
aito = 'h1st_contrib.cli:h1st_cli'


[build-system]
requires = [
  'Poetry-Core >= 1.0.8',
]
build-backend = 'poetry.core.masonry.api'
